module.exports = {
  "id": 254225,
  "slug": "barstool-twitter",
  "name": "Barstool Twitter",
  "plan": "enterprise",
  "update_frequency": 1440,
  "last_synced": "2018-03-15T03:43:02.014-07:00",
  "max_sources": 1000,
  "more_sources_allowed?": true,
  "analytics_allowed?": true,
  "moderation_allowed?": true,
  "css": "modern",
  "interval": 5000,
  "width": 600,
  "height": null,
  "columns": 1,
  "order": "created_at",
  "display_filter": null,
  "display_filter_type": true,
  "colored_icons": false,
  "photos": false,
  "videos": false,
  "lazy_load": false,
  "overlay": true,
  "video_overlay": false,
  "infinite_scroll": true,
  "poll": false,
  "disallowed": null,
  "allowed": null,
  "distance": null,
  "location": null,
  "lat": null,
  "lng": null,
  "profanity": false,
  "prevent_duplicates": false,
  "queue": false,
  "moderating": false,
  "page_views_count": 0,
  "custom_css": null,
  "colors": {
    "text_color": null,
    "link_color": null,
    "data_color": null,
    "hover_color": null,
    "post_background_color": null,
    "feed_background_color": null
  },
  "style": "modern",
  "requested_at": "2018-03-15T06:32:35.141-07:00",
  "posts": {
    "current_page": 1,
    "limit_value": 100,
    "items": [
      {
        "id": 211789859,
        "external_id": "974120484089614336",
        "external_created_at": "2018-03-14T20:09:56.000-07:00",
        "full_url": "https://twitter.com/stoolpresidente/status/974120484089614336",
        "image": "https://pbs.twimg.com/media/DYTFaZtVAAAWDK1.jpg",
        "external": null,
        "like_count": 2490,
        "comment_count": 383,
        "tagged_users": null,
        "poster_url": "https://www.twitter.com/stoolpresidente",
        "poster_id": "43775786",
        "location": null,
        "height": 1536,
        "width": 2048,
        "edit": null,
        "position": null,
        "deleted_at": null,
        "deleted_by": null,
        "additional_photos": null,
        "message": "<p>When you can’t hit your free throws in March <a target=\"_blank\" class=\"auto\" href=\"https://t.co/WrjvCxDi8Z\">https://t.co/WrjvCxDi8Z</a></p>",
        "unformatted_message": "When you can’t hit your free throws in March https://t.co/WrjvCxDi8Z",
        "description": null,
        "feed": "barstool-twitter",
        "likes": 2490,
        "comments": 383,
        "poster_image": "https://pbs.twimg.com/profile_images/598493860336148480/SaR7gKvr_normal.jpg",
        "poster_name": "stoolpresidente",
        "poster_display_name": "Dave Portnoy",
        "source": {
          "id": 414242,
          "term": "stoolpresidente",
          "term_type": "username",
          "source": "Twitter",
          "options": "retweets,replies",
          "name": null,
          "allowed": null,
          "disallowed": null,
          "queue": false
        }
      },
      {
        "id": 211789855,
        "external_id": "974168542001225728",
        "external_created_at": "2018-03-14T23:20:54.000-07:00",
        "full_url": "https://twitter.com/BarstoolNate/status/974168542001225728",
        "image": null,
        "external": "https://twitter.com/CT_DUVAL/status/974168248198541312",
        "like_count": 102,
        "comment_count": 9,
        "tagged_users": null,
        "poster_url": "https://www.twitter.com/BarstoolNate",
        "poster_id": "216766313",
        "location": null,
        "height": null,
        "width": null,
        "edit": null,
        "position": null,
        "deleted_at": null,
        "deleted_by": null,
        "additional_photos": null,
        "message": "<p>600,000 people are watching him, commercial free, at 2am. I want to say 500k seems....low. <a href='https://t.co/CySVV6wizF' target='_blank'>twitter.com/CT_DUVAL/statu…</a></p>",
        "unformatted_message": "600,000 people are watching him, commercial free, at 2am. I want to say 500k seems....low. <a href='https://t.co/CySVV6wizF' target='_blank'>twitter.com/CT_DUVAL/statu…</a>",
        "description": null,
        "feed": "barstool-twitter",
        "likes": 102,
        "comments": 9,
        "poster_image": "https://pbs.twimg.com/profile_images/965817196915122176/k78XBSc2_normal.jpg",
        "poster_name": "BarstoolNate",
        "poster_display_name": "Nate",
        "source": {
          "id": 414247,
          "term": "barstoolnate",
          "term_type": "username",
          "source": "Twitter",
          "options": "retweets,replies",
          "name": null,
          "allowed": null,
          "disallowed": null,
          "queue": false
        }
      },
      {
        "id": 211789852,
        "external_id": "974111277827133441",
        "external_created_at": "2018-03-14T19:33:15.000-07:00",
        "full_url": "https://twitter.com/CrazedPackRat/status/974111277827133441",
        "image": "https://pbs.twimg.com/tweet_video_thumb/DYS9AutVAAE26B9.jpg",
        "external": null,
        "like_count": 82,
        "comment_count": 9,
        "tagged_users": "BarstoolBigCat",
        "poster_url": "https://www.twitter.com/CrazedPackRat",
        "poster_id": "35177597",
        "location": null,
        "height": 212,
        "width": 384,
        "edit": null,
        "position": null,
        "deleted_at": null,
        "deleted_by": null,
        "additional_photos": null,
        "message": "<p><div class='j-reply j-twitter-meta'>Replying to <a href='https://www.twitter.com/BarstoolBigCat' target='_blank'>@BarstoolBigCat</a></div><div class='j-retweet j-twitter-meta'>Retweeted by <a href='https://www.twitter.com/BarstoolBigCat' target='_blank'>Big Cat</a></div><a href='https://twitter.com/BarstoolBigCat' target='_blank'>@BarstoolBigCat</a>  </p>",
        "unformatted_message": "<div class='j-reply j-twitter-meta'>Replying to <a href='https://www.twitter.com/BarstoolBigCat' target='_blank'>@BarstoolBigCat</a></div><div class='j-retweet j-twitter-meta'>Retweeted by <a href='https://www.twitter.com/BarstoolBigCat' target='_blank'>Big Cat</a></div><a href='https://twitter.com/BarstoolBigCat' target='_blank'>@BarstoolBigCat</a>  ",
        "description": null,
        "feed": "barstool-twitter",
        "likes": 82,
        "comments": 9,
        "video": "https://video.twimg.com/tweet_video/DYS9AutVAAE26B9.mp4",
        "poster_image": "https://pbs.twimg.com/profile_images/477955799877038080/UoMGA-GH_normal.jpeg",
        "poster_name": "CrazedPackRat",
        "poster_display_name": "-Ike",
        "source": {
        "id": 414243,
        "term": "barstoolbigcat",
        "term_type": "username",
        "source": "Twitter",
        "options": "retweets,replies",
        "name": null,
        "allowed": null,
        "disallowed": null,
        "queue": false
        }
      }
    ]
  }
}